"""empty message

Revision ID: 93240e16d20d
Revises: 4fda9fe9e347
Create Date: 2026-03-26 15:09:53.295050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93240e16d20d'
down_revision: Union[str, Sequence[str], None] = '4fda9fe9e347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Integer(), nullable=True), schema='task_management')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active', schema='task_management')
    # ### end Alembic commands ###
